[package]
name = "rss-funnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async runtime, utility and helper crates
async-trait = "0.1.74"
thiserror = "1.0.51"
futures = "0.3.29"
itertools = "0.12.0"
tokio = { version = "1.35.0", features = ["macros", "net", "rt-multi-thread"] }

# Command line and config parsing
clap = { version = "4.4.11", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"

# Feed formats support
atom_syndication = "0.12.2"
rss = "2.0.6"

# Web server
axum = "0.7.2"
tower = "0.4.13"
http = "1.0.0"
url = "2.5.0"

# HTML manipulation in the feeds
scraper = "0.18.1"
ego-tree = "0.6.2"
# for extracting article content from HTML, used in simplify_html filter
readability = { version = "0.3.0", default-features = false }

# JS runtime crates
rquickjs = { version = "0.4.0", features = ["loader", "parallel", "macro", "futures", "exports"] }
blake2s_simd = "1.0.2" # for calculating digest in caching support of the remote loader
serde_json = "1.0.108" # for data transfer with the JS runtime

# Web client (blocking and async both used, blocking used in the JS runtime)
# TODO: upgrade reqwest after its hyper 1.0 upgrade
reqwest = { version = "0.11.23", default-features = false, features = ["blocking", "rustls-tls", "trust-dns"] }

# Used in sanitize filter to remove/replace text contents
regex = "1.10.2"

# Logging
tracing = { version = "0.1.40"}
tracing-subscriber = "0.3.18"
duration-str = { version = "0.7.1", default-features = false, features = ["serde"] }
